{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "my-app-gitlabci.fullname" . -}}
  {{- $svcPort := .Values.service.port -}}
  {{- $hostProduction := .Values.ingress.hostProduction -}}
  {{- $hostTesting := .Values.ingress.hostTesting -}}
  {{- $hostStaging := .Values.ingress.hostStaging -}}
  {{- $ingressPath := .Values.ingress.path -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    helm.sh/chart: {{ include "my-app-gitlabci.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if eq $.Values.ingress.featureName "my-app-gitlabci-testing" }}
    {{- range $hostTesting }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
    {{- end }}           
    {{- else if eq $.Values.ingress.featureName "my-app-gitlabci-staging" }}
    {{- range $hostStaging }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
    {{- end }} 
    {{- else if eq $.Values.ingress.featureName "my-app-gitlabci" }}
    {{- range $hostProduction }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
    {{- end }}
    {{- end }}  
{{- end }}