---
- hosts: all
  become: True
  become_user: "{{ become_user }}"
  vars:
    chdir_path: /home/danhnt
  tasks:
  - name: Go to the folder and execute command
    args:
      chdir: '{{ chdir_path }}'
    command: ls
    register: output
  - debug: var=output.stdout_lines

  - name: Git Clone Crawler
    args:
      chdir: '{{ chdir_path }}/crawler'
    # command: git clone ssh://git@git.example.com/crawler.git --branch master 
    shell: |
      git checkout master
      git pull origin master
    register: output
  - debug: var=output.stdout_lines

  - name: Git Clone Pattern-Manager
    args:
      chdir: '{{ chdir_path }}/pattern-manager'
    # command: git clone ssh://git@git.example.com/pattern-manager.git --branch master 
    shell: |
      git checkout master
      git pull origin master
    register: output
  - debug: var=output.stdout_lines

  - name: Run forever restart all
    command: "{{ forever }} restartall"
    register: output
  - debug: var=output.stdout_lines
